[tasks.default-icon]
cwd = "src/IconDownloader"
command = "dotnet"
args = ["run", "--name", "${@}", "--out", "../../tmp"]

[tasks.bold-icon]
cwd = "src/IconDownloader"
command = "dotnet"
args = ["run", "--name", "${@}", "--style", "bold", "--out", "../../tmp"]
